/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as OrientacoesRouteImport } from './routes/orientacoes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientacoesRoute = OrientacoesRouteImport.update({
  id: '/orientacoes',
  path: '/orientacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orientacoes': typeof OrientacoesRoute
  '/publications': typeof PublicationsRoute
  '/software': typeof SoftwareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orientacoes': typeof OrientacoesRoute
  '/publications': typeof PublicationsRoute
  '/software': typeof SoftwareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/orientacoes': typeof OrientacoesRoute
  '/publications': typeof PublicationsRoute
  '/software': typeof SoftwareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/orientacoes' | '/publications' | '/software'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/orientacoes' | '/publications' | '/software'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/orientacoes'
    | '/publications'
    | '/software'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OrientacoesRoute: typeof OrientacoesRoute
  PublicationsRoute: typeof PublicationsRoute
  SoftwareRoute: typeof SoftwareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientacoes': {
      id: '/orientacoes'
      path: '/orientacoes'
      fullPath: '/orientacoes'
      preLoaderRoute: typeof OrientacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OrientacoesRoute: OrientacoesRoute,
  PublicationsRoute: PublicationsRoute,
  SoftwareRoute: SoftwareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
